
platform :ios, '9.0'
use_frameworks!
target 'bigWeiAPP' do

pod 'UITableView+FDTemplateLayoutCell', '~> 1.6’
pod 'FMDB', '~> 2.7.2’
pod 'SDWebImage', '~> 3.7.6’
pod 'MJRefresh’,'~> 3.1.12’
pod 'MJExtension', '~> 3.0.13’
pod 'MBProgressHUD', '0.9'
pod 'Masonry', '~> 1.0.2’
pod 'AFNetworking'
pod 'IQKeyboardManager'
pod 'MagicalRecord', '~> 2.0'
pod 'Base64'
pod 'SSKeychain', '~> 1.4.1'
pod 'ReactiveCocoa', '~> 2.5’
pod 'Reachability', '~> 3.2'
pod 'CocoaLumberjack', '~> 2.0'



end
